app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::resource('tasks', 'TasksController');

app/Tasks.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tasks extends Model
{
    protected $fillable = ['title', 'body'];
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Tasks;
use Redirect;
use Illuminate\Support\Facades\Input;

class TasksController extends Controller
{
    /**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
    public function index()
    {
    	$tasks = Tasks::orderBy('id')->get();
		return view('tasks.index',compact('tasks'));

    }

    /**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
    public function create()
    {
    	return view('tasks.create');
    }

    /**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$tasks = Tasks::create(Input::all());
		return Redirect::route('tasks.index');
	}

}

resources/views/tasks/create.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <title>Cadastro de Tarefa</title>	  
</head>
<body>
  <form action="{!!URL::route('tasks.store')!!}" method="post">
    <label for="titulo">Título:</label>
    <input type="text" name="title">
    <label for="corpo">Corpo:</label>
    <input type="text" name="body">    
    <input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}" />
    <input type="submit">
  </form>
</body>
</html>	

resources/views/tasks/index.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <title>Lista de Tarefas</title>
</head>
<body>
  <ul>
  <?php foreach ($tasks as $tarefa): ?>
    <li>
        Id: <?php echo $tarefa->id ?>
        <br/>
        Título: <?php echo $tarefa->title ?>
        <br/>
        Corpo: <?php echo $tarefa->body ?>
    </li>
  <?php endforeach ?>
  </ul>
  <a href="{!!URL::route('tasks.create')!!}">Cadastro</a>
</body>
</html>